# -*- coding: utf-8 -*-
"""flask_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R94PPegFtcizfUYjDUi9MI2BkfjxQ4_4
"""

import sys
import os
import traceback
import logging
from flask import Flask, request, jsonify

# Set up logging
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s')

# Add the parent directory to the system path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from document_processing import process_query  # Import the function from document_processing.py
app = Flask(__name__)

@app.route('/', methods=['POST'])
def handle_query():
    try:
        # Use request.json for JSON payloads
        data = request.json
        query = data.get('question')
        if not query:
            return jsonify({"error": "No question provided"}), 400

        # Process the query
        logging.debug(f"Received query: {query}")
        answer = process_query(query)  # Use the process_query function
        response = {"answer": answer}
        return jsonify(response)
    except Exception as e:
        logging.error(f"Error handling query: {e}")
        return jsonify({"error": "Internal server error"}), 500

if __name__ == '__main__':
    app.run(debug=True, port=5001)  # Ensure port 5001 is used